on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - events.csv

jobs:
  updateEventData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
